# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import main
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")
print(OUTPUT_PATH,ASSETS_PATH)
window = Tk()

window.geometry("850x420")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=420,
    width=850,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)
output_label = canvas.create_text(
    89.0,
    368.0,
    anchor="nw",
    text="Will be save in: ",
    fill="#000000",
    font=("Kokoro Regular", 16 * -1)
)
songs_source = ''
output_path = ''


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def uploadAction(event=None):
    global songs_source
    songs_source = filedialog.askopenfilename(filetypes=(('text files', '.txt'),))


def chooseFolderAction(event=None):
    global output_path, canvas, output_label
    output_path = filedialog.askdirectory()
    canvas.itemconfigure(output_label, text="Will be save in: " + output_path)


def download(event=None):
    global songs_source, output_path, entry_1
    is_link_related = False
    youtube_link = entry_1.get()
    if youtube_link:
        songs_source = youtube_link
        is_link_related = True
    main.download_song(songs_source, output_path, is_link_related)


canvas.place(x=0, y=0)

canvas.create_text(
    225.0,
    24.0,
    anchor="nw",
    text="Music Downloader",
    fill="#000000",
    font=("Nunito Bold", 48 * -1)
)

button_image_1 = PhotoImage(  # choose folder
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: chooseFolderAction(),
    relief="flat"
)
button_1.place(
    x=89.0,
    y=214.0,
    width=201.0,
    height=116.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(  # open text file
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: uploadAction(),
    relief="flat"
)
button_2.place(
    x=89.0,
    y=123.0,
    width=201.0,
    height=59.0
)

button_image_3 = PhotoImage(  # download songs
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: download(),
    relief="flat"
)

button_3.place(
    x=470.0,
    y=214.0,
    width=298.0,
    height=116.0
)

canvas.create_text(
    354.0,
    253.0,
    anchor="nw",
    text="AND",
    fill="#000000",
    font=("Kokoro Regular", 24 * -1)
)

canvas.create_text(
    312.0,
    140.0,
    anchor="nw",
    text="OR enter URL:",
    fill="#000000",
    font=("Kokoro Regular", 24 * -1)
)


entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    619.0,
    160.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    highlightthickness=0
)
entry_1.place(
    x=486.5,
    y=144.0,
    width=265.0,
    height=31.0
)
window.resizable(False, False)
window.mainloop()
